### ISSUE TITLE
Generating null sets

### ISSUE THREAD

**Issue by sa-lee** [nullranges/nullranges#1]
Pulling in some thoughts from slack.

I am currently thinking we have all the null generators as closures that have the potential to take a BPARAM so we could do the null set generation in parallel and over chromsomes / design.  

```{r}
generator <- simple_shuffle(.parallel = bparam, ... # other params)
class(generator) # engen, function
```
A user could also roll their own generator using this approach. 
   
There would be a generic function (sampler) that accepts ranges objects plus a null generator and spits out the bootstrapped / matched set of ranges either as List or a Ranges or  GroupedRanges object.

**Comment by mikelove** [comment]
Thanks Stuart for starting to put down these thoughts. This sounds like the right approach, but I'm too ignorant about how it would be coded. In 3f71c4e I've started to write basic R functions for bootstrapping ranges. It doesn't do much but maybe it's enough of a foundation for you to experiment with the null generator idea?

**Comment by sa-lee** [comment]
closing this for now as I think we've moved beyond it
