### ISSUE TITLE
gfortran required for DNAcopy

### ISSUE THREAD

**Issue by mdozmorov** [nullranges/nullranges#20]
On macOS Ventura 13.0.1, nullranges fails to install. The probmen is DNAcopy package that requires gfortran. Error is

```r
Error: package or namespace load failed for ‘DNAcopy’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Users/mdozmorov/Library/R/x86_64/4.2/library/DNAcopy/libs/DNAcopy.so':
  dlopen(/Users/mdozmorov/Library/R/x86_64/4.2/library/DNAcopy/libs/DNAcopy.so, 0x0006): Symbol not found: __gfortran_os_error_at
  Referenced from: <63BB7839-FF14-3647-A153-9067DE724969> /Users/mdozmorov/Library/R/x86_64/4.2/library/DNAcopy/libs/DNAcopy.so
  Expected in:     <5B0F7278-9D16-3B60-A413-59EEF538E568> /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libgfortran.5.dylib
```

gfortran can be installed with homebrew as a part of gcc formula. But R still cannot recognize it. I tried various advice, like https://support.bioconductor.org/p/9141978/, nothing works. GitHub actions also fail on this package https://github.com/mdozmorov/nullranges/actions/runs/3508177212/jobs/5876402915. Somebody recommended https://github.com/fxcoudert/gfortran-for-macOS/releases, but it currently lacks an installer for Intel-based Macs. 

The good news is that nullranges works in Docker.
```bash
docker run -e PASSWORD=mypass -p 8787:8787 -d --rm -v $(pwd):/home/rstudio bioconductor/bioconductor_docker:RELEASE_3_16
```

**Comment by mikelove** [comment]
This is a bummer. It's just a Suggests but it's annoying in terms of testing the package that we have to deal with gfortran.

However, we tended to like CBS over HMM.

**Comment by s-u** [comment]
Please see CRAN for the Fortran compiler used by R, you need to instal it for packages that require Fortran to compile (see https://mac.r-project.org/tools/)

**Comment by mdozmorov** [comment]
Thanks, Simon. I tried installing [gfortran-8.2-Mojave.dmg](https://mac.r-project.org/tools/gfortran-8.2-Mojave.dmg) from https://mac.r-project.org/tools/, followed instructions, restarted the computer - same issue (Xcode already installed). I looked at https://github.com/fxcoudert/gfortran-for-macOS/releases, but it lacks gfortran release for Intel-based computers. 

Per @vjcitn advice, I tried fixing links as at the bottom of the page https://bioconductor.org/checkResults/3.16/bioc-mac-arm64-LATEST/DNAcopy/kjohnson-buildbin.html. Downloaded/extracted macOS Binary (x86_64)	[DNAcopy_1.72.0.tgz](https://bioconductor.org/packages/release/bioc/bin/macosx/contrib/4.2/DNAcopy_1.72.0.tgz) and tried:
```bash
install_name_tool -change "/usr/local/Cellar/gcc/12.2.0/lib/gcc/current/libgcc_s.1.1.dylib" "/Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libgcc_s.1.1.dylib" "DNAcopy/libs/DNAcopy.so"
install_name_tool -change "/usr/local/Cellar/gcc/12.2.0/lib/gcc/current/libgfortran.5.dylib" "/Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libgfortran.5.dylib" "DNAcopy/libs/DNAcopy.so"
install_name_tool -change "/usr/local/Cellar/gcc/12.2.0/lib/gcc/current/libquadmath.0.dylib" "/Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libquadmath.0.dylib" "DNAcopy/libs/DNAcopy.so"
```

Honestly, I do not fully understand what these commands are doing. They output no messages. I may be doing things incorrectly because they didn't have any effect. I opened an issue in the DNAcopy GitHub repo https://github.com/veseshan/DNAcopy/issues/6

**Comment by mikelove** [comment]
Unrelated, I’ve got GitHub actions working on nullranges, it wasn’t related in my case to DNAcopy. So if you’re at your wits end with gfortran you don’t need it (you can just rely on GHA for the quick package check and vignette building).

**Comment by s-u** [comment]
@mdozmorov you have to remove Homebrew - it completely breaks the compilers, that's why nothing works and it's using the wrong compilers that are incompatible.

**Comment by mikelove** [comment]
I think we've resolved this sufficiently, e.g. should work with binaries provided by Bioc now.

**Comment by guriaregojo** [comment]
Hello I'm running github actions and in macOS I am getting an error when running maftools::read.maf, specifically the issue is related to this DNAcopy package and gfortran. I attach a picture of the failed job:
<img width="714" alt="Screenshot 2023-01-17 at 09 40 51" src="https://user-images.githubusercontent.com/73877383/212849782-1461f0fd-0401-4ded-992f-766c91e6f434.png">

Is there any way to fix this? Thank you for your time
