### ISSUE TITLE
Extend plyranges to apply to GInteractions objects

### ISSUE THREAD

**Issue by mikelove** [nullranges/nullranges#25]

**Comment by EricSDavis** [comment]
Do you think this warrants a separate package (i.e. `plyinteractions`)? Will all of the functions translate to situations where there are paired `GRanges` and maybe there are some additional functions that only apply to paired ranges?

**Comment by EricSDavis** [comment]
Maybe this warrants a separate issue, but there are also a few small quality of life features that could be added to `InteractionSet`. 

A few examples:

- logical indexing of `GInteractions` objects.
- adding dollar names methods for RStudio autocomplete for mcol `$` selection.
- built in coercion of bedpe-formatted data.frames to `GInteractions` objects. (Currently implemented in [mariner](https://github.com/EricSDavis/mariner))
- Direct accessors for anchor components (`seqnames1`, `start1`, `end1`, etc.) (Currently implemented in [mariner](https://github.com/EricSDavis/mariner))

**Comment by mikelove** [comment]
I think it makes sense to break off as a new package, mostly for ease of development.

You know this space better than me, but I’d be happy to bounce ideas around (we can find a time to chat at BioC)

**Comment by js2264** [comment]
Hi @mikelove @EricSDavis, I'd be happy to contribute to this project as well, would that be ok for you?
I am familiar with `InteractionSet` and `plyranges`, and I'd love to work towards combining both worlds. I guess a dedicated `plyinteractions` would make sense.

**Comment by EricSDavis** [comment]
Hi @js2264, happy to work together on this!

**Comment by js2264** [comment]
New 📦 available @ [`tidyomics/plyinteractions`](https://github.com/tidyomics/plyinteractions)

**Comment by mikelove** [comment]
If you want, we can move the open challenge from here to your new package location.

Start by creating a new Issue "Extend plyranges to apply to GInteractions objects" on your repo, then add that to the Open Challenges, and remove this one.

**Comment by js2264** [comment]
This one should be closed now. Thanks @mikelove!
