### ISSUE TITLE
Un-segmented block bootstrap

### ISSUE THREAD

**Issue by mikelove** [nullranges/nullranges#7]
* `deny` argument - two options, toss the overlaps, or trim (warn users in docs)
* return `R` multiple bootstraps

**Comment by Wancen** [comment]
For the within chr function, I think it will be faster and save memory if you change 
 ```
random_blocks <- GRanges(
    seqnames=chr,
    IRanges(start = round(runif(n, 1, (n - 1) * L_b + 1)), width = L_b)
  )
  # where those blocks will move to
  rearranged_blocks <- GRanges(
    seqnames=chr,
    successiveIRanges(width(random_blocks))
  )
  # the shift needed to move them
  block_shift <- start(rearranged_blocks) - start(random_blocks)
  # use the bait to sample features in 'x'
  fo <- findOverlaps(random_blocks, x)
```
to the IRanges because we only need the start of them. Previously taking 1.7s and now takes 1s~
```
random_blocks <- IRanges(start = round(runif(n, 1, (n - 1) * L_b + 1)), width = L_b)

  # where those blocks will move to
  rearranged_blocks <- successiveIRanges(width(random_blocks))

  # the shift needed to move them
  block_shift <- start(rearranged_blocks) - start(random_blocks)
  # use the bait to sample features in 'x'
  fo <- findOverlaps(random_blocks, ranges(x))
```

**Comment by mikelove** [comment]
Agree, thanks. I also applied this to the permute function: 64ea403

**Comment by sa-lee** [comment]
One advantage of using the GRanges approach, is that you could stack multiple replicates in a GRangesList, so you could do the overlaps simultaneously using the findOverlaps machinery, but the block_shift approach would need to be tweaked a bit. 
i.e.
```r
R <- 1000
random_blocks <- GRangesList(
   replicate(R, GRanges(seqnames=chr, ranges = IRanges(start = round(runif(n, 1, (n - 1) * L_b + 1)), width = L_b)))
)
```

**Comment by Wancen** [comment]
That's a great point! Oh, I have to change the current code to only bootstraps for random_blocks, it's a waste that builds rearranged_blocks multiple times!

**Comment by mikelove** [comment]
I think this is all covered now
